In [1]:
import torch
import torch.nn as nn

# 定义一个简单的神经网络模型
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)


In [2]:

# 使用@torch.no_grad()装饰器的函数
@torch.no_grad()
def no_grad_function():
    model = SimpleModel()
    print("Before updating weights:")
    print("Weight:", model.linear.weight)
    # 在no_grad_function中，即使对权重进行了更改，也不会被记录
    model.linear.weight.fill_(2.0)
    print("After updating weights:")
    print("Weight:", model.linear.weight)


print("Testing with @torch.no_grad() decorator:")
no_grad_function()


Testing with @torch.no_grad() decorator:
Before updating weights:
Weight: Parameter containing:
tensor([[0.3450]], requires_grad=True)
After updating weights:
Weight: Parameter containing:
tensor([[2.]], requires_grad=True)


In [4]:
# 不使用@torch.no_grad()装饰器的函数
def normal_function():
    model = SimpleModel()
    print("Before updating weights:")
    print("Weight:", model.linear.weight)
    model.linear.weight.fill_(2.0)
    print("After updating weights:")
    print("Weight:", model.linear.weight)

print("\nTesting without @torch.no_grad() decorator:")
normal_function()


Testing without @torch.no_grad() decorator:
Before updating weights:
Weight: Parameter containing:
tensor([[-0.6426]], requires_grad=True)


RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.